name: CI/CD MLOps Quality Gate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Lint, Test & Model Quality Gate
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: 'pip'

    - name: Install Dependencies
      run: make install

    - name: Code Quality & Linting
      run: make lint

    - name: Unit Tests & MLOps Quality Gate
      run: make test
